### ISSUE TITLE
Practica de elicitacion

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/practica-de-elicitacion-de-requisitos-disttecpersis#1]
[Practica elicitacion de requisitos-1.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-elicitacion-de-requisitos-disttecpersis/files/7575640/Practica.elicitacion.de.requisitos-1.pdf)

**Comment by Abraham890** [comment]
Calificacion: 30/30 Puntos

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/143180243-413d2fe2-1940-4161-b2bd-7a49da40cc5d.png)
Esos no son los requisitos de informacion

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/143180424-bc5b4f05-ce55-4b95-9f24-42c4b833aa85.png)
Los requisitos de informacion deben estar redactados en infinitivo

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/143180532-535cc98e-c968-41c9-b178-b5f7b6138c16.png)
Estos son requisitos que NO funcionales...pero no estan bien redactados...no puede haber un requsito No funcional que se llame INTERFAZ,....

**Comment by salathiel1999** [comment]
ya lo corregimos
[Practica elicitacion de requisitos-corregido.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-elicitacion-de-requisitos-disttecpersis/files/7610642/Practica.elicitacion.de.requisitos-corregido.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado, no era necesario en esta practica hacerlo en architech
